Repository Doong-Ji/nestalk-frontend, pull requests merged in 2021-03, with the labels that each got.

#32 [style] global theme type checking, Responsive design add
  package-lock.json
  package.json
  src/theme/index.ts
  src/theme/styled.d.ts
Labels: :100: must, :national_park: environment

#36 Feature/common part
  public/css/reset.css
  public/css/variables.css
  public/image/icon/add_circle_outline-24px.svg
  public/image/icon/add_comment-24px.svg
  public/image/icon/arrow_upward-24px.svg
  public/image/icon/chat_bubble-24px.svg
  public/image/icon/close-24px.svg
  public/image/icon/edit-24px.svg
  public/image/icon/keyboard_arrow_left-24px.svg
  public/image/icon/local_see-24px.svg
  public/image/icon/menu-24px.svg
  public/image/icon/more_horiz-24px.svg
  public/image/icon/perm_identity-24px.svg
  public/image/icon/search-24px.svg
  public/image/icon/settings-24px.svg
  public/index.html
Labels: 👩‍💻markup

#42 add user icon
  public/image/icon/user-620px.png
Labels: 🐣 feature

#39 친구 추가 및 프로필 html 구현
  public/modal-friend.html
Labels: 🐣 feature, 👩‍💻markup

#38 Feature/chat list
  public/css/list-chat.css
  public/css/reset.css
  public/list-chat.html
Labels: 🐣 feature, 👩‍💻markup

#46 edit code
  public/css/reset.css
  public/css/variables.css
Labels: 🐣 feature, 👩‍💻markup

#51 Feature/ list chat revise
  .gitignore
  public/css/list-chat.css
  public/list-chat.html
Labels: 🐣 feature, 👩‍💻markup

#47 add list-friend html/css
  public/css/list-friend.css
  public/image/icon/chat_bubble_outline-24px.svg
  public/list-friend.html
Labels: 🐣 feature, 👩‍💻markup

#61 Feature/Modal-chat | basic setting
  public/css/modal-chat.css
  public/modal-chat.html
Labels: 🐣 feature, 👩‍💻markup

#49 채팅방 목록 조회, 기본 메뉴 레이아웃 구현
  package-lock.json
  package.json
  src/components/frames/AppLayout/AppLayout.tsx
  src/components/frames/Header/Header.tsx
  src/components/frames/Header/index.ts
  src/components/frames/Header/styled.ts
  src/components/frames/Menu/Menu.tsx
  src/components/frames/Menu/index.ts
  src/components/frames/Menu/styled.ts
  src/components/pages/Home/Home.tsx
  src/hooks/useChatRoom.ts
  src/hooks/useRootState.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/reducers/chat/index.ts
  src/reducers/chat/roomAdd.ts
  src/reducers/chat/roomList.ts
  src/reducers/index.ts
  src/reducers/loadingtype.ts
  src/reducers/user/index.ts
  src/sagas/chat/index.ts
  src/sagas/chat/roomList.ts
  src/sagas/index.ts
  src/types/chatting.ts
  tsconfig.json
Labels: 🐣 feature, 👨‍💻frontend

#65 ssr sample code 적용
  package-lock.json
  src/components/frames/AppLayout/AppLayout.tsx
  src/components/frames/Menu/Menu.tsx
  src/components/pages/Home/Home.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/reducers/chat/index.ts
  src/reducers/chat/roomAdd.ts
  src/reducers/chat/roomList.ts
  src/store/configureStore.ts
Labels: 🐣 feature, 👨‍💻frontend

#64 Feature/#48 modal add friend
  public/css/modal-friend.css
  public/modal-friend.html
Labels: 🐣 feature, 👩‍💻markup

#62 Feature/Modal chat | chatting room
  public/css/modal-chat.css
  public/css/reset.css
  public/modal-chat.html
Labels: 🐣 feature, 👩‍💻markup

#63 Feature/Modal-chat | search modal from chatting room
  public/css/modal-chat.css
  public/modal-chat.html
Labels: 🐣 feature, 👩‍💻markup

#68 conflict resolution
  public/css/modal-chat.css
  public/modal-chat.html
Labels: 👩‍💻markup, 🔧 refactor
